name: Humans of The Grid
favicon: null
layout_spectrum: 0.45318870851770043
typography_spectrum: 0.9639239620883018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-9927803-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.051795718260109425
purpose: []
